# Generated by Django 5.2.5 on 2025-08-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("doctor", "Врач"), ("patient", "Пациент")],
                default="patient",
                max_length=10,
            ),
        ),
    ]
