version: '3.8'
services:
  web:
    build: .
    ports:
      - "9052:8000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DEBUG=1
    depends_on:
      - db

    command: sh -c 'poetry install && poetry run python manage.py runserver 0.0.0.0:8000'

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD:  ${PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
