# Generated by Django 5.2.5 on 2025-08-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_date", models.DateTimeField()),
                ("reason", models.TextField()),
                ("is_confirmed", models.BooleanField(default=False)),
                ("appointment_datetime", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждена"),
                            ("cancelled", "Отменена"),
                            ("completed", "Завершена"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(max_length=100)),
                (
                    "equipment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("узи", "УЗИ-аппарат"),
                            ("рентген", "Рентген-аппарат"),
                            ("экг", "ЭКГ-аппарат"),
                            ("мрт", "МРТ"),
                            ("кт", "КТ"),
                            ("", "Без оборудования"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                ("specialization", models.TextField()),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("B+", "B+"),
                            ("AB+", "AB+"),
                            ("O+", "O+"),
                            ("A-", "A-"),
                            ("B-", "B-"),
                            ("AB-", "AB-"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название услуги"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Стоимость"
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(default=30, verbose_name="Длительность (мин)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название категории"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-псевдоним, генерируется автоматически из названия.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание категории"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Чем меньше число, тем выше категория в списке.",
                        verbose_name="Порядок отображения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория услуги",
                "verbose_name_plural": "Категории услуг",
                "ordering": ["order", "name"],
            },
        ),
    ]
