# Generated by Django 5.2.5 on 2025-08-21 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medsite", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="appointment_datetime",
        ),
        migrations.AddField(
            model_name="appointment",
            name="appointment_time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
