# Generated by Django 5.2.5 on 2025-08-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medsite", "0003_remove_appointment_appointment_datetime_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="duration",
        ),
        migrations.AddField(
            model_name="service",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=30),
        ),
    ]
