# Generated by Django 5.2.5 on 2025-08-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medsite", "0004_remove_service_duration_service_duration_minutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="reason",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
