# Generated by Django 5.2.5 on 2025-08-24 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medsite", "0006_feedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="diagnosis",
            field=models.TextField(blank=True, verbose_name="Диагноз"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Примечания врача"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="results",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="diagnostics/",
                verbose_name="Результаты",
            ),
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="medsite.appointment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
