# Generated by Django 5.2.5 on 2025-08-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medsite", "0010_remove_patient_address_remove_patient_blood_group_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="birth_date",
            new_name="birth_day",
        ),
    ]
