# Generated by Django 5.2.5 on 2025-08-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medsite", "0011_rename_birth_date_patient_birth_day"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="diagnosis",
            new_name="diagnosis_text",
        ),
    ]
