# Generated by Django 5.2.5 on 2025-08-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medsite", "0012_rename_diagnosis_appointment_diagnosis_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointment_date",
            field=models.DateField(),
        ),
    ]
