# Generated by Django 5.2.5 on 2025-08-29 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "medsite",
            "0015_remove_diagnosis_results_remove_diagnosis_updated_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diagnosis",
                to="medsite.appointment",
                verbose_name="Приём",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пациент",
            ),
        ),
    ]
