# Generated by Django 5.2.5 on 2025-08-29 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medsite", "0016_alter_diagnosis_appointment_alter_diagnosis_patient"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diagnosis",
            old_name="diagnosis_text",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="diagnosis",
            name="created_at",
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="diagnosis_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diagnoses",
                to="medsite.appointment",
                verbose_name="Приём",
            ),
        ),
    ]
