# Generated by Django 5.2.5 on 2025-08-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medsite", "0017_rename_diagnosis_text_diagnosis_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="diagnosis_text",
            new_name="description",
        ),
    ]
