# Generated by Django 5.2.5 on 2025-08-31 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medsite", "0020_alter_appointment_doctor_alter_appointment_patient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="medsite.doctor",
                verbose_name="Врач",
            ),
        ),
    ]
