# Generated by Django 5.2.5 on 2025-08-31 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medsite", "0021_alter_appointment_doctor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="reason",
        ),
        migrations.AddField(
            model_name="appointment",
            name="diagnoses",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments_diagnoses",
                to="medsite.diagnosis",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnoses_set",
                to="medsite.appointment",
            ),
        ),
    ]
