# Generated by Django 5.2.5 on 2025-09-01 20:15

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medsite", "0025_alter_appointment_diagnoses"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="end_time",
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name="doctor",
            name="start_time",
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
